apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
  labels:
    app: mypvc
spec:
  storageClassName: managed-csi-premium
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

